English Translation added to README file
olivierperez/kata-shame-on-it pull request #6
Opened 2019-10-09 19:23 UTC by khanaaziz1

English Translation added to README file

2019-10-09 21:03 UTC, olivierperez requested changes
Thanks a lot for translation :smile:
Can you?
- look at the comments
- move the english part to another file (`en/README.md`)
- Add a chapter in the main README "Other languages" that list translations

2019-10-09 21:03 UTC, olivierperez commented on README.md
> +I learned how to use the brakes on my downhill bike, and not just use the brake
Do we say "front brake" in english? To talk about the brake of the front wheel?

2019-10-09 21:03 UTC, olivierperez commented on README.md
> +the experience that was hers at that time. He'll do better next time, that's for sure.
"was hers" -> "was his/hers"?

2019-10-09 21:03 UTC, olivierperez commented on README.md
> +analyze ([snippets] (/ kotlin / snippets /)). The idea is that each group has snippets
The link is broken

2019-10-09 21:03 UTC, olivierperez commented on README.md
> +### :mag_right: Running the kata (10-15 minutes by snippets)
by snippet (minus "s")

2019-10-09 21:03 UTC, olivierperez commented on README.md
> +### :mega: Pooling (5 minutes by snippets)
same

2019-10-10 14:14 UTC, khanaaziz1 commented
lemme go through it again :)

2019-10-10 15:16 UTC, khanaaziz1 commented
you can review now

2019-10-11 08:38 UTC, olivierperez requested changes
One last change please :-)

2019-10-11 08:38 UTC, olivierperez commented on README_OtherLanguages.md
> +analyze ([snippets](/kotlin/snippets/)). The idea is that each group has snippet
```suggestion
analyze ([snippets](/snippets/)). The idea is that each group has snippet
```

2019-10-11 12:13 UTC, khanaaziz1 commented on README_OtherLanguages.md
> +analyze ([snippets](/kotlin/snippets/)). The idea is that each group has snippet
done

2019-10-11 12:21 UTC, olivierperez approved these changes

2019-10-11 12:22 UTC, olivierperez commented
There are some conflicts, I can't merged.
Otherwise, it looks good to me.

2019-10-11 12:26 UTC, khanaaziz1 commented
let me check

2019-10-11 12:44 UTC, khanaaziz1 commented
is it ok if i refork and upload the file again

2019-10-11 12:51 UTC, closed without merging